### ISSUE TITLE
layer not building

### ISSUE THREAD

**Issue by aversag** [z0ph/s3-backup-notifier#1]
hi,
i've tried this package as I'm moving my backup to S3 but can't make it work.

it seems that the "make layer" command doesn't build the layer for the lambda.

so it's missing when building the lambda function :

Layer version arn:aws:lambda:eu-west-3:722738461861:layer:boto3-layer:15 does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: bd15f46b-f9fa-4247-984e-f1973673c303)

by adding "boto3" and "botocore" in requirements.txt file I'm getting some files in layer, but no zip uploaded to my bucket

deployer:~/s3-backup-notifier# make layer
mkdir -p layer
pip3 install \
                --isolated \
                --disable-pip-version-check \
                -Ur ./python/requirements.txt -t ./layer/
Collecting boto3 (from -r ./python/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/27/87/de75e5a24584d82cca60b86f95d06e56412ed9e23807dcf23896f206f58e/boto3-1.12.39-py2.py3-none-any.whl
Collecting botocore (from -r ./python/requirements.txt (line 2))

  Using cached https://files.pythonhosted.org/packages/dc/fb/f78a0e09965c156fea9160713705af688ec4f18af4249b3095949c930f77/botocore-1.15.39-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->-r ./python/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a3/43/1e939e1fcd87b827fe192d0c9fc25b48c5b3368902bfb913de7754b0dc03/jmespath-0.9.5-py2.py3-none-any.whl
Collecting s3transfer<0.4.0,>=0.3.0 (from boto3->-r ./python/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from botocore->-r ./python/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version != "3.4" (from botocore->-r ./python/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore->-r ./python/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore->-r ./python/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: jmespath, docutils, urllib3, six, python-dateutil, botocore, s3transfer, boto3
Successfully installed boto3-1.12.39 botocore-1.15.39 docutils-0.15.2 jmespath-0.9.5 python-dateutil-2.8.1 s3transfer-0.3.3 six-1.14.0 urllib3-1.25.8
deployer:~/s3-backup-notifier# l layer
total 104
drwxr-xr-x  3 root root  4096 Apr 14 13:22 bin
drwxr-xr-x 10 root root  4096 Apr 14 13:22 boto3
drwxr-xr-x  2 root root  4096 Apr 14 13:22 boto3-1.12.39.dist-info
drwxr-xr-x  7 root root  4096 Apr 14 13:22 botocore
drwxr-xr-x  2 root root  4096 Apr 14 13:22 botocore-1.15.39.dist-info
drwxr-xr-x  6 root root  4096 Apr 14 13:22 dateutil
drwxr-xr-x  9 root root  4096 Apr 14 13:22 docutils
drwxr-xr-x  2 root root  4096 Apr 14 13:22 docutils-0.15.2.dist-info
drwxr-xr-x  3 root root  4096 Apr 14 13:22 jmespath
drwxr-xr-x  2 root root  4096 Apr 14 13:22 jmespath-0.9.5.dist-info
drwxr-xr-x  2 root root  4096 Apr 14 13:22 __pycache__
drwxr-xr-x  2 root root  4096 Apr 14 13:22 python_dateutil-2.8.1.dist-info
drwxr-xr-x  3 root root  4096 Apr 14 13:22 s3transfer
drwxr-xr-x  2 root root  4096 Apr 14 13:22 s3transfer-0.3.3.dist-info
drwxr-xr-x  2 root root  4096 Apr 14 13:22 six-1.14.0.dist-info
-rw-r--r--  1 root root 34074 Apr 14 13:22 six.py
drwxr-xr-x  6 root root  4096 Apr 14 13:22 urllib3
drwxr-xr-x  2 root root  4096 Apr 14 13:22 urllib3-1.25.8.dist-info

**Comment by z0ph** [comment]
Sorry didn't see your issue, are you still experiencing issue?

**Comment by aversag** [comment]
No problem
I've forked your project and solved my issue
thank you!
